## YAML Config File.
## PRODUCTION environment.
app:
    codename: rmanager

debug:
    mode: false

log:
    level: error

database:
    driver: pdo_mysql
    host: localhost
    dbname:
    user: root
    password:
    charset: utf8
